name: Bug report
description: Report a reproducible bug in TaskX
title: "bug: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue. Please provide deterministic reproduction details.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction Steps
      description: Exact commands, inputs, and environment.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: proof
    attributes:
      label: Proof Bundle
      description: Paste command output (`git status --porcelain`, logs, traces).
    validations:
      required: true
